import { ProductNutrients } from '../types/product';

interface CategoryBenchmark {
  keywords: string[];
  nutrients: ProductNutrients;
  servingSize: string;
  servingGrams: number;
  categoryLabel: string;
}

export const CATEGORY_BENCHMARKS: CategoryBenchmark[] = [
  {
    keywords: ['chip', 'crisp', 'tortilla', 'dorito', 'nacho', 'lays', 'potato chips', 'pringles', 'kurkure', 'namkeen'],
    servingSize: '30 g (approx. 15 chips)',
    servingGrams: 30,
    categoryLabel: 'Savory Snacks / Chips',
    nutrients: {
      calories: 520,
      protein: 6.5,
      carbohydrates: 56.0,
      sugars: 2.5,
      addedSugars: 0.5,
      fat: 30.0,
      saturatedFat: 4.5,
      fiber: 3.8,
      sodium: 580,
      salt: 1.45,
    },
  },
  {
    keywords: ['cookie', 'biscuit', 'oreo', 'bourbon', 'digestive', 'parle', 'marie', 'wafer', 'shortbread'],
    servingSize: '25 g (2-3 biscuits)',
    servingGrams: 25,
    categoryLabel: 'Biscuits & Cookies',
    nutrients: {
      calories: 480,
      protein: 5.8,
      carbohydrates: 68.0,
      sugars: 34.0,
      addedSugars: 32.0,
      fat: 20.0,
      saturatedFat: 7.5,
      fiber: 2.2,
      sodium: 320,
      salt: 0.8,
    },
  },
  {
    keywords: ['dark chocolate', 'cocoa 70', 'cocoa 85', 'noir'],
    servingSize: '30 g (3 squares)',
    servingGrams: 30,
    categoryLabel: 'Dark Chocolate',
    nutrients: {
      calories: 575,
      protein: 9.0,
      carbohydrates: 36.0,
      sugars: 22.0,
      addedSugars: 20.0,
      fat: 42.0,
      saturatedFat: 25.0,
      fiber: 10.5,
      sodium: 25,
      salt: 0.06,
    },
  },
  {
    keywords: ['chocolate', 'candy', 'snickers', 'kitkat', 'cadbury', 'milky bar', 'twix', 'mars bar'],
    servingSize: '45 g (1 bar)',
    servingGrams: 45,
    categoryLabel: 'Milk Chocolates & Confectionery',
    nutrients: {
      calories: 515,
      protein: 7.2,
      carbohydrates: 59.0,
      sugars: 50.0,
      addedSugars: 45.0,
      fat: 28.0,
      saturatedFat: 15.0,
      fiber: 2.5,
      sodium: 140,
      salt: 0.35,
    },
  },
  {
    keywords: ['noodle', 'ramen', 'maggi', 'instant noodles', 'cup noodles', 'chow mein'],
    servingSize: '70 g (1 pack)',
    servingGrams: 70,
    categoryLabel: 'Instant Noodles / Ramen',
    nutrients: {
      calories: 440,
      protein: 8.5,
      carbohydrates: 62.0,
      sugars: 2.5,
      addedSugars: 1.0,
      fat: 17.5,
      saturatedFat: 7.5,
      fiber: 3.2,
      sodium: 1150,
      salt: 2.88,
    },
  },
  {
    keywords: ['soda', 'cola', 'coca', 'pepsi', 'sprite', 'fanta', 'soft drink', 'carbonated', 'thums up'],
    servingSize: '330 ml (1 can)',
    servingGrams: 330,
    categoryLabel: 'Sweetened Soft Drinks',
    nutrients: {
      calories: 42,
      protein: 0.0,
      carbohydrates: 10.6,
      sugars: 10.6,
      addedSugars: 10.6,
      fat: 0.0,
      saturatedFat: 0.0,
      fiber: 0.0,
      sodium: 10,
      salt: 0.02,
    },
  },
  {
    keywords: ['zero sugar', 'diet cola', 'coke zero', 'diet pepsi', 'sugar free drink'],
    servingSize: '330 ml (1 can)',
    servingGrams: 330,
    categoryLabel: 'Zero Sugar Beverages',
    nutrients: {
      calories: 1,
      protein: 0.0,
      carbohydrates: 0.1,
      sugars: 0.0,
      addedSugars: 0.0,
      fat: 0.0,
      saturatedFat: 0.0,
      fiber: 0.0,
      sodium: 25,
      salt: 0.06,
    },
  },
  {
    keywords: ['peanut butter', 'almond butter', 'nut butter', 'skippy', 'jif'],
    servingSize: '32 g (2 tbsp)',
    servingGrams: 32,
    categoryLabel: 'Nut Butters',
    nutrients: {
      calories: 590,
      protein: 24.0,
      carbohydrates: 19.0,
      sugars: 8.5,
      addedSugars: 5.0,
      fat: 50.0,
      saturatedFat: 9.5,
      fiber: 7.0,
      sodium: 380,
      salt: 0.95,
    },
  },
  {
    keywords: ['greek yogurt', 'fage', 'chobani', 'skyr', 'high protein yogurt'],
    servingSize: '150 g (3/4 cup)',
    servingGrams: 150,
    categoryLabel: 'Greek Yogurt',
    nutrients: {
      calories: 60,
      protein: 10.5,
      carbohydrates: 3.6,
      sugars: 3.6,
      addedSugars: 0.0,
      fat: 0.5,
      saturatedFat: 0.2,
      fiber: 0.0,
      sodium: 40,
      salt: 0.1,
    },
  },
  {
    keywords: ['yogurt', 'curd', 'dahi', 'plain yogurt'],
    servingSize: '150 g',
    servingGrams: 150,
    categoryLabel: 'Yogurt / Fermented Dairy',
    nutrients: {
      calories: 65,
      protein: 4.5,
      carbohydrates: 6.0,
      sugars: 5.5,
      addedSugars: 0.0,
      fat: 3.2,
      saturatedFat: 2.0,
      fiber: 0.0,
      sodium: 55,
      salt: 0.14,
    },
  },
  {
    keywords: ['butter', 'amul butter', 'margarine', 'ghee', 'makhan'],
    servingSize: '14 g (1 tbsp)',
    servingGrams: 14,
    categoryLabel: 'Butter & Solid Fats',
    nutrients: {
      calories: 720,
      protein: 0.8,
      carbohydrates: 0.6,
      sugars: 0.6,
      addedSugars: 0.0,
      fat: 80.0,
      saturatedFat: 50.0,
      fiber: 0.0,
      sodium: 700,
      salt: 1.75,
    },
  },
  {
    keywords: ['cheese', 'cheddar', 'mozzarella', 'paneer', 'parmesan', 'gouda'],
    servingSize: '30 g (1 slice/cube)',
    servingGrams: 30,
    categoryLabel: 'Cheese & Dairy Blocks',
    nutrients: {
      calories: 360,
      protein: 22.0,
      carbohydrates: 2.5,
      sugars: 0.5,
      addedSugars: 0.0,
      fat: 29.0,
      saturatedFat: 18.0,
      fiber: 0.0,
      sodium: 620,
      salt: 1.55,
    },
  },
  {
    keywords: ['bread', 'toast', 'loaf', 'bun', 'bagel', 'pita', 'naan', 'roti', 'chapati', 'tortilla wrap'],
    servingSize: '40 g (1 slice / 1 piece)',
    servingGrams: 40,
    categoryLabel: 'Bread & Bakery',
    nutrients: {
      calories: 265,
      protein: 8.5,
      carbohydrates: 49.0,
      sugars: 4.5,
      addedSugars: 2.5,
      fat: 3.5,
      saturatedFat: 0.8,
      fiber: 3.8,
      sodium: 460,
      salt: 1.15,
    },
  },
  {
    keywords: ['oat', 'oatmeal', 'quaker', 'porridge', 'rolled oats', 'muesli'],
    servingSize: '40 g (1/2 cup dry)',
    servingGrams: 40,
    categoryLabel: 'Oats & Whole Grains',
    nutrients: {
      calories: 380,
      protein: 12.5,
      carbohydrates: 66.0,
      sugars: 1.5,
      addedSugars: 0.0,
      fat: 7.0,
      saturatedFat: 1.2,
      fiber: 10.0,
      sodium: 5,
      salt: 0.01,
    },
  },
  {
    keywords: ['cereal', 'corn flakes', 'cheerios', 'granola', 'chocos', 'loops'],
    servingSize: '30 g (1 cup)',
    servingGrams: 30,
    categoryLabel: 'Breakfast Cereals',
    nutrients: {
      calories: 375,
      protein: 8.0,
      carbohydrates: 78.0,
      sugars: 18.0,
      addedSugars: 16.0,
      fat: 3.0,
      saturatedFat: 0.7,
      fiber: 4.5,
      sodium: 450,
      salt: 1.12,
    },
  },
  {
    keywords: ['milk', 'dairy milk', 'whole milk', 'toned milk', 'cow milk'],
    servingSize: '240 ml (1 cup)',
    servingGrams: 240,
    categoryLabel: 'Milk',
    nutrients: {
      calories: 62,
      protein: 3.3,
      carbohydrates: 4.8,
      sugars: 4.8,
      addedSugars: 0.0,
      fat: 3.4,
      saturatedFat: 2.1,
      fiber: 0.0,
      sodium: 45,
      salt: 0.11,
    },
  },
  {
    keywords: ['plant milk', 'almond milk', 'oat milk', 'soy milk', 'oatly', 'silk'],
    servingSize: '240 ml (1 cup)',
    servingGrams: 240,
    categoryLabel: 'Plant-Based Milks',
    nutrients: {
      calories: 45,
      protein: 1.5,
      carbohydrates: 5.5,
      sugars: 3.0,
      addedSugars: 0.0,
      fat: 2.2,
      saturatedFat: 0.3,
      fiber: 1.0,
      sodium: 65,
      salt: 0.16,
    },
  },
  {
    keywords: ['ketchup', 'tomato sauce', 'sauce', 'pasta sauce', 'marinara'],
    servingSize: '20 g (1 tbsp)',
    servingGrams: 20,
    categoryLabel: 'Sauces & Condiments',
    nutrients: {
      calories: 110,
      protein: 1.5,
      carbohydrates: 24.0,
      sugars: 20.0,
      addedSugars: 17.0,
      fat: 0.3,
      saturatedFat: 0.0,
      fiber: 1.5,
      sodium: 850,
      salt: 2.12,
    },
  },
  {
    keywords: ['oil', 'olive oil', 'cooking oil', 'sunflower oil', 'mustard oil'],
    servingSize: '15 ml (1 tbsp)',
    servingGrams: 14,
    categoryLabel: 'Vegetable & Cooking Oils',
    nutrients: {
      calories: 884,
      protein: 0.0,
      carbohydrates: 0.0,
      sugars: 0.0,
      addedSugars: 0.0,
      fat: 100.0,
      saturatedFat: 14.5,
      fiber: 0.0,
      sodium: 0,
      salt: 0.0,
    },
  },
  {
    keywords: ['protein bar', 'energy bar', 'rxbar', 'quest bar', 'granola bar'],
    servingSize: '50 g (1 bar)',
    servingGrams: 50,
    categoryLabel: 'Protein & Energy Bars',
    nutrients: {
      calories: 400,
      protein: 22.0,
      carbohydrates: 40.0,
      sugars: 18.0,
      addedSugars: 8.0,
      fat: 16.0,
      saturatedFat: 3.5,
      fiber: 8.0,
      sodium: 350,
      salt: 0.88,
    },
  },
  {
    keywords: ['beans', 'black beans', 'kidney beans', 'chickpeas', 'lentils', 'rajma', 'chana', 'dal'],
    servingSize: '130 g (1/2 cup cooked)',
    servingGrams: 130,
    categoryLabel: 'Beans & Legumes',
    nutrients: {
      calories: 115,
      protein: 7.5,
      carbohydrates: 20.0,
      sugars: 0.8,
      addedSugars: 0.0,
      fat: 0.6,
      saturatedFat: 0.1,
      fiber: 6.5,
      sodium: 80,
      salt: 0.2,
    },
  },
  {
    keywords: ['rice', 'basmati', 'brown rice', 'white rice'],
    servingSize: '150 g (1 cup cooked)',
    servingGrams: 150,
    categoryLabel: 'Rice & Grains',
    nutrients: {
      calories: 130,
      protein: 2.7,
      carbohydrates: 28.0,
      sugars: 0.1,
      addedSugars: 0.0,
      fat: 0.3,
      saturatedFat: 0.1,
      fiber: 0.6,
      sodium: 2,
      salt: 0.01,
    },
  },
];

/**
 * Match a product's name, brand, or categories to standard nutritional benchmarks
 */
export function estimateNutrientsFromTitle(
  name: string,
  brand?: string,
  categories?: string[]
): {
  nutrients100g: ProductNutrients;
  nutrientsServing: ProductNutrients;
  servingSize: string;
  servingGrams: number;
  categoryLabel: string;
} | null {
  const fullText = `${name} ${brand || ''} ${(categories || []).join(' ')}`.toLowerCase();

  for (const bench of CATEGORY_BENCHMARKS) {
    for (const kw of bench.keywords) {
      if (fullText.includes(kw)) {
        const ratio = bench.servingGrams / 100;
        const nutrientsServing: ProductNutrients = {
          calories: Math.round(bench.nutrients.calories * ratio),
          protein: Number((bench.nutrients.protein * ratio).toFixed(1)),
          carbohydrates: Number((bench.nutrients.carbohydrates * ratio).toFixed(1)),
          sugars: Number((bench.nutrients.sugars * ratio).toFixed(1)),
          addedSugars: bench.nutrients.addedSugars !== undefined ? Number((bench.nutrients.addedSugars * ratio).toFixed(1)) : undefined,
          fat: Number((bench.nutrients.fat * ratio).toFixed(1)),
          saturatedFat: Number((bench.nutrients.saturatedFat * ratio).toFixed(1)),
          fiber: Number((bench.nutrients.fiber * ratio).toFixed(1)),
          sodium: Math.round(bench.nutrients.sodium * ratio),
          salt: Number((bench.nutrients.salt * ratio).toFixed(2)),
        };

        return {
          nutrients100g: { ...bench.nutrients },
          nutrientsServing,
          servingSize: bench.servingSize,
          servingGrams: bench.servingGrams,
          categoryLabel: bench.categoryLabel,
        };
      }
    }
  }

  return null;
}
