# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use AndroidX (mandatory for Jetpack Compose, CameraX, Room, and modern Android libraries)
android.useAndroidX=true

# Enables namespacing for each library's R class
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official
